AWSTemplateFormatVersion: 2010-09-09

Description: >-
  AWS SAM template used to deploy a TypeScript backend with Webpack

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    Handler: dist/app.handler
    MemorySize: 128
    Timeout: 3
    AutoPublishAlias: live
    Tracing: Active
    Environment:
      Variables:
        REGION: !Ref AWS::Region

Resources:
  AwsGlobalLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: AWS dependencies global layer
      ContentUri: layers/global-layers/aws-global-layer
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs12.x

  CommonGlobalLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Common dependencies global layer
      ContentUri: layers/global-layers/common-global-layer
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs12.x

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Hello function
      CodeUri: functions/hello-function
      Layers:
        - !Ref HelloFunctionLayer
        - !Ref CommonGlobalLayer
        - !Ref AwsGlobalLayer

  HelloFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Hello function layer
      ContentUri: layers/function-layers/hello-function-layer
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs12.x

  GoodbyeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Goodbye function
      CodeUri: functions/goodbye-function
      Layers:
        - !Ref GoodbyeFunctionLayer
        - !Ref CommonGlobalLayer

  GoodbyeFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Goodbye function layer
      ContentUri: layers/function-layers/goodbye-function-layer
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs12.x

Outputs:
  StackName:
    Description: Stack name
    Value: !Ref AWS::StackName
  StackArn:
    Description: Stack ARN
    Value: !Ref AWS::StackId
  StackRegion:
    Description: Stack region
    Value: !Ref AWS::Region

  AwsGlobalLayerArn:
    Description: AWS dependencies global layer ARN
    Value: !Ref AwsGlobalLayer
  CommonGlobalLayerArn:
    Description: Common dependencies global layer ARN
    Value: !Ref CommonGlobalLayer

  HelloFunctionName:
    Description: Hello function name
    Value: !Ref HelloFunction
  HelloFunctionArn:
    Description: Hello function ARN
    Value: !GetAtt HelloFunction.Arn
  HelloFunctionLayerArn:
    Description: Hello function layer ARN
    Value: !Ref HelloFunctionLayer

  GoodbyeFunctionName:
    Description: Goodbye function name
    Value: !Ref GoodbyeFunction
  GoodbyeFunctionArn:
    Description: Goodbye function ARN
    Value: !GetAtt GoodbyeFunction.Arn
  GoodbyeFunctionLayerArn:
    Description: Goodbye function layer ARN
    Value: !Ref GoodbyeFunctionLayer
