AWSTemplateFormatVersion: 2010-09-09

Description: >-
  AWS SAM template used to deploy a TypeScript backend with Webpack

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  ApiStageName:
    Type: String
    Description: The name of the stage, which API Gateway uses as the first path segment in the invoke Uniform Resource Identifier (URI).
    Default: dev
  ApiVersion:
    Type: String
    Description: The version identifier of the API documentation snapshot.
    Default: 1.0.0
  AutoPublishAlias:
    Type: String
    Description: Name of the Lambda alias.
    Default: live

Globals:
  Api:
    EndpointConfiguration:
      Type: REGIONAL
    OpenApiVersion: 3.0.3
    TracingEnabled: true
  Function:
    Runtime: nodejs12.x
    Handler: dist/app.handler
    MemorySize: 128
    Timeout: 3
    AutoPublishAlias: !Ref AutoPublishAlias
    Tracing: Active
    Environment:
      Variables:
        REGION: !Ref AWS::Region

Resources:
  CustomerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName
      DefinitionBody: !Transform { Name: AWS::Include, Parameters: { Location: openapi/customer.yaml } }

  CustomerApiDocumentation:
    Type: AWS::ApiGateway::DocumentationVersion
    Properties:
      RestApiId: !Ref CustomerApi
      DocumentationVersion: !Ref ApiVersion

  CustomerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: partitionKey
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: partitionKey
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  ApplicationLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Application layer
      ContentUri: layers/application-layer
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs12.x

  CreateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Create customer function
      CodeUri: functions/create-customer-function
      Layers:
        - !Ref ApplicationLayer
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          CUSTOMER_TABLE_NAME: !Ref CustomerTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref CustomerTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref CustomerApi
            Path: /customers
            Method: post

Outputs:
  StackName:
    Description: Stack name
    Value: !Ref AWS::StackName
  StackArn:
    Description: Stack ARN
    Value: !Ref AWS::StackId
  StackRegion:
    Description: Stack region
    Value: !Ref AWS::Region

  CustomerApiId:
    Description: Customer API ID
    Value: !Ref CustomerApi
  CustomerApiUrl:
    Description: Customer API URL
    Value: !Sub https://${CustomerApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/

  CustomerTableName:
    Description: Customer table name
    Value: !Ref CustomerTable
  CustomerTableArn:
    Description: Customer table ARN
    Value: !GetAtt CustomerTable.Arn

  ApplicationLayerArn:
    Description: Application layer ARN
    Value: !Ref ApplicationLayer

  CreateCustomerFunctionName:
    Description: Create customer function name
    Value: !Ref CreateCustomerFunction
  CreateCustomerFunctionArn:
    Description: Create customer function ARN
    Value: !GetAtt CreateCustomerFunction.Arn
